services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVE_FRONTEND=true
      - FRONTEND_DIR=frontend/dist
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
